const CUSTOMER_SITES = {
    feifan: { name: "非凡资源", api: "http://ffzy5.tv/api.php/provide/vod" },
    wolong: { name: "卧龙资源", api: "https://wolongzyw.com/api.php/provide/vod" },
    zuida: { name: "最大资源", api: "https://api.zuidapi.com/api.php/provide/vod" },
    baiduyun: { name: "百度云资源", api: "https://api.apibdzy.com/api.php/provide/vod" },
    baofeng: { name: "暴风资源", api: "https://bfzyapi.com/api.php/provide/vod" },
    jisu: { name: "极速资源", api: "https://jszyapi.com/api.php/provide/vod" },
    tianya: { name: "天涯资源", api: "https://tyyszy.com/api.php/provide/vod" },
    wujin: { name: "无尽资源", api: "https://api.wujinapi.com/api.php/provide/vod" },
    modu: { name: "魔都资源", api: "https://www.mdzyapi.com/api.php/provide/vod" },
    sanliuling: { name: "360资源", api: "https://360zy.com/api.php/provide/vod" },
    dytt: { name: "电影天堂", api: "http://caiji.dyttzyapi.com/api.php/provide/vod" },
    ruyi: { name: "如意资源", api: "https://cj.rycjapi.com/api.php/provide/vod" },
    wangwang: { name: "旺旺资源", api: "https://wwzy.tv/api.php/provide/vod" },
    hongniu: { name: "红牛资源", api: "https://www.hongniuzy2.com/api.php/provide/vod" },
    guangsu: { name: "光速资源", api: "https://api.guangsuapi.com/api.php/provide/vod" },
    ikun: { name: "iKun资源", api: "https://ikunzyapi.com/api.php/provide/vod" },
    youku: { name: "优酷资源", api: "https://api.ukuapi.com/api.php/provide/vod" },
    huya: { name: "虎牙资源", api: "https://www.huyaapi.com/api.php/provide/vod" },
    xinlang: { name: "新浪资源", api: "http://api.xinlangapi.com/xinlangapi.php/provide/vod" },
    lezi: { name: "乐子资源", api: "https://cj.lziapi.com/api.php/provide/vod" },
    haihua: { name: "海豚资源", api: "https://hhzyapi.com/api.php/provide/vod" },
    jiangyu: { name: "鲸鱼资源", api: "https://jyzyapi.com/provide/vod" },
    aidan: { name: "爱蛋资源", api: "https://lovedan.net/api.php/provide/vod" },
    moduzy: { name: "魔都影视", api: "https://www.moduzy.com/api.php/provide/vod" },
    feifanapi: { name: "非凡API", api: "https://api.ffzyapi.com/api.php/provide/vod" },
    feifancj: { name: "非凡采集", api: "http://cj.ffzyapi.com/api.php/provide/vod" },
    feifancj2: { name: "非凡采集HTTPS", api: "https://cj.ffzyapi.com/api.php/provide/vod" },
    feifan1: { name: "非凡线路1", api: "http://ffzy1.tv/api.php/provide/vod" },
    wolong2: { name: "卧龙采集", api: "https://collect.wolongzyw.com/api.php/provide/vod" },
    baofeng2: { name: "暴风APP", api: "https://app.bfzyapi.com/api.php/provide/vod" },
    wujin2: { name: "无尽ME", api: "https://api.wujinapi.me/api.php/provide/vod" },
    tianyazy: { name: "天涯海角", api: "https://tyyszyapi.com/api.php/provide/vod" },
    guangsu2: { name: "光速HTTP", api: "http://api.guangsuapi.com/api.php/provide/vod" },
    xinlang2: { name: "新浪HTTPS", api: "https://api.xinlangapi.com/xinlangapi.php/provide/vod" },
    yilingba2: { name: "1080JSON", api: "https://api.1080zyku.com/inc/apijson.php" },
    lezi2: { name: "乐子HTTP", api: "http://cj.lziapi.com/api.php/provide/vod" },
    uku88: { name: "U酷资源88", api: "https://api.ukuapi88.com/api.php/provide/vod" },
    wujincc: { name: "无尽CC", api: "https://api.wujinapi.cc/api.php/provide/vod" },
    yaya: { name: "丫丫点播", api: "https://cj.yayazy.net/api.php/provide/vod" },
    wolongcc: { name: "卧龙CC", api: "https://collect.wolongzy.cc/api.php/provide/vod" },
    wangwangapi: { name: "旺旺API", api: "https://api.wwzy.tv/api.php/provide/vod" },
    zuidame: { name: "最大点播", api: "http://zuidazy.me/api.php/provide/vod" },
    yinghua: { name: "樱花资源", api: "https://m3u8.apiyhzy.com/api.php/provide/vod" },
    bubugao: { name: "步步高资源", api: "https://api.yparse.com/api/json" },
    niuniu: { name: "牛牛点播", api: "https://api.niuniuzy.me/api.php/provide/vod" },
    suoni: { name: "索尼资源", api: "https://suoniapi.com/api.php/provide/vod" },
    maotai: { name: "茅台资源", api: "https://caiji.maotaizy.cc/api.php/provide/vod" },
    dbzy: { name: "豆瓣资源", api: "https://dbzy.tv/api.php/provide/vod" },
    subo: { name: "速博资源", api: "https://subocaiji.com/api.php/provide/vod" },
    jinying: { name: "金鹰点播", api: "https://jinyingzy.com/api.php/provide/vod" },
    shandian: { name: "閃電资源", api: "https://sdzyapi.com/api.php/provide/vod" },
    piaoling: { name: "飘零资源", api: "https://p2100.net/api.php/provide/vod" },
    modudongman: { name: "魔都动漫", api: "https://caiji.moduapi.cc/api.php/provide/vod" },
    hongniu3: { name: "红牛资源3", api: "https://www.hongniuzy3.com/api.php/provide/vod" },
    suonisd: { name: "索尼-闪电", api: "https://xsd.sdzyapi.com/api.php/provide/vod" },
    leba: { name: "乐播资源", api: "https://lbapi9.com/api.php/provide/vod" },
    ck: { name: "CK", api: "https://www.ckzy1.com/api.php/provide/vod" },
    jkun: { name: "jkun", api: "https://jkunzyapi.com/api.php/provide/vod" },
    155: { name: "155", api: "https://155api.com/api.php/provide/vod" },
    lsb: { name: "lsb", api: "https://apilsbzy1.com/api.php/provide/vod" },
    hsck: { name: "黄色仓库", api: "https://hsckzy.vip/api.php/provide/vod" },
    yutu: { name: "玉兔", api: "https://yutuzy10.com/api.php/provide/vod" },
    msnii: { name: "美少女资源站", api: "https://www.msnii.com/api/json.php" },
    xrbsp: { name: "淫水机资源站", api: "https://www.xrbsp.com/api/json.php" },
    gdlsp: { name: "香奶儿资源站", api: "https://www.gdlsp.com/api/json.php" },
    kxgav: { name: "白嫖资源站", api: "https://www.kxgav.com/api/json.php" },
    pgxdy: { name: "黄AV资源站", api: "https://www.pgxdy.com/api/json.php" },
    baiwan: { name: "百万资源", api: "https://api.bwzyz.com/api.php/provide/vod" },
    madou: { name: "91麻豆", api: "https://91md.me/api.php/provide/vod" },
    aosika: { name: "奥斯卡资源", api: "https://aosikazy.com/api.php/provide/vod" },
    naixiang: { name: "奶香香", api: "https://Naixxzy.com/api.php/provide/vod" },
    senlin: { name: "森林资源", api: "https://slapibf.com/api.php/provide/vod" },
    fanhao: { name: "番号资源", api: "http://fhapi9.com/api.php/provide/vod" },
    jingpin: { name: "精品资源", api: "https://www.jingpinx.com/api.php/provide/vod" },
    shayu: { name: "鲨鱼资源", api: "https://shayuapi.com/api.php/provide/vod" },
    xiaoji: { name: "小鸡资源", api: "https://api.xiaojizy.live/provide/vod" },
    xibao: { name: "细胞采集", api: "https://www.xxibaozyw.com/api.php/provide/vod" },
    wujinnet: { name: "无尽NET", api: "https://api.wujinapi.net/api.php/provide/vod" }
};

// 调用全局方法合并
if (window.extendAPISites) {
    window.extendAPISites(CUSTOMER_SITES);
} else {
    console.error("错误：请先加载 config.js！");
}
